//
//  AddEditAlbumConfigurator.swift
//  PrivateCorner
//
//  Created by a on 4/3/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AddEditAlbumInteractor: AddEditAlbumViewControllerOutput, AddEditAlbumRouterDataSource, AddEditAlbumRouterDataDestination {
}

extension AddEditAlbumPresenter: AddEditAlbumInteractorOutput {
}

class AddEditAlbumConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = AddEditAlbumConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: AddEditAlbumViewController) {
        
        let presenter = AddEditAlbumPresenter()
        presenter.output = viewController
        
        let interactor = AddEditAlbumInteractor()
        interactor.output = presenter
        
        let router = AddEditAlbumRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
