//
//  AddEditAlbumInteractor.swift
//  PrivateCorner
//
//  Created by a on 4/3/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AddEditAlbumInteractorInput {
    
}

protocol AddEditAlbumInteractorOutput {
    
}

protocol AddEditAlbumDataSource {
    
}

protocol AddEditAlbumDataDestination {
    
}

class AddEditAlbumInteractor: AddEditAlbumInteractorInput, AddEditAlbumDataSource, AddEditAlbumDataDestination {
    
    var output: AddEditAlbumInteractorOutput!
    
    // MARK: Business logic
    

}
