//
//  AddEditAlbumPresenter.swift
//  PrivateCorner
//
//  Created by a on 4/3/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AddEditAlbumPresenterInput {
    
}

protocol AddEditAlbumPresenterOutput: class {
    
}

class AddEditAlbumPresenter: AddEditAlbumPresenterInput {
    
    weak var output: AddEditAlbumPresenterOutput!
    
    // MARK: Presentation logic
    
}
