//
//  AddEditAlbumRouter.swift
//  PrivateCorner
//
//  Created by a on 4/3/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AddEditAlbumRouterInput {
    
}

protocol AddEditAlbumRouterDataSource:class {
    
}

protocol AddEditAlbumRouterDataDestination:class {
    
}

class AddEditAlbumRouter: AddEditAlbumRouterInput {
    
    weak var viewController:AddEditAlbumViewController!
    weak private var dataSource:AddEditAlbumRouterDataSource!
    weak var dataDestination:AddEditAlbumRouterDataDestination!
    
    init(viewController:AddEditAlbumViewController, dataSource:AddEditAlbumRouterDataSource, dataDestination:AddEditAlbumRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
