//
//  AddEditAlbumViewController.swift
//  PrivateCorner
//
//  Created by a on 4/3/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AddEditAlbumViewControllerInput {
    
}

protocol AddEditAlbumViewControllerOutput {
    
}

class AddEditAlbumViewController: UIViewController, AddEditAlbumViewControllerInput {
    
    var output: AddEditAlbumViewControllerOutput!
    var router: AddEditAlbumRouter!
    
    // MARK: Object lifecycle
    
    var isEditAlbum: Bool = false
    
    override func awakeFromNib() {
        super.awakeFromNib()
        AddEditAlbumConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Event handling
    
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension AddEditAlbumViewController: AddEditAlbumPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(for: segue)
    }
}
