//
//  AlbumsInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AlbumsInteractorInput {
    
}

protocol AlbumsInteractorOutput {
    
}

protocol AlbumsDataSource {
    
}

protocol AlbumsDataDestination {
    
}

class AlbumsInteractor: AlbumsInteractorInput, AlbumsDataSource, AlbumsDataDestination {
    
    var output: AlbumsInteractorOutput!
    
    // MARK: Business logic
    

}
