//
//  AlbumsViewController.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol AlbumsViewControllerInput {
    func displayAlbums(viewModel: AlbumsScene.GetAlbum.ViewModel)
}

protocol AlbumsViewControllerOutput {
    func getAlbum(request:AlbumsScene.GetAlbum.Request)
}

class AlbumsViewController: UIViewController, AlbumsViewControllerInput {
    
    var output: AlbumsViewControllerOutput!
    var router: AlbumsRouter!
    var albums:[Album] = []
    
    @IBOutlet weak var albumsCollectionView: UICollectionView!
    
    // MARK: Object lifecycle
    
    struct cellIdentifiers {
        static let albumsCell = "albumsCell"
    }
    
    struct cellLayout {
        static let itemsPerRow: CGFloat = 2
        static let sectionInsets: UIEdgeInsets = UIEdgeInsets(top: 16, left: 16, bottom: 16, right: 16)
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
        AlbumsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.title = "Album"
        configureCollectionViewOnLoad()
        getAlbumFromCoreData()
    }
    
    // MARK: Event handling
    
    func configureCollectionViewOnLoad() {
        let nibName = UINib(nibName: "AlbumsCell", bundle:Bundle.main)
        albumsCollectionView.register(nibName, forCellWithReuseIdentifier: cellIdentifiers.albumsCell)
    }
    
    func getAlbumFromCoreData() {
        let request = AlbumsScene.GetAlbum.Request()
        output.getAlbum(request: request)
    }
    
    func selectedGalleryAtIndex(index: Int) {
        
        
        router.navigateToGalleryScreen()
    }
    
    @IBAction func addAlbumButtonItemTapped(_ sender: Any) {
        let alert = UIAlertController.init(title: "New Album", message: "Enter a name for this album", preferredStyle: .alert)
        alert.addTextField { (textField) in
            textField.keyboardType = .alphabet
            textField.placeholder = "Title"
        }
        
        let cancelAction = UIAlertAction.init(title: "Cancel", style: .cancel, handler: nil)
        alert.addAction(cancelAction)
        
        let saveAction = UIAlertAction.init(title: "Save", style: .default) { (action) in
            let textField = alert.textFields?.first
        }
        alert.addAction(saveAction)

        self.present(alert, animated: true, completion: nil)
    }

    @IBAction func editAlbumButtonItemTapped(_ sender: Any) {
        
    }
    
    // MARK: Display logic
    func displayAlbums(viewModel: AlbumsScene.GetAlbum.ViewModel) {
        albums = viewModel.albums
        albumsCollectionView.reloadData()
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension AlbumsViewController: AlbumsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(for: segue)
    }
}
