//
//  FolderListConfigurator.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension FolderListInteractor: FolderListViewControllerOutput, FolderListRouterDataSource, FolderListRouterDataDestination {
}

extension FolderListPresenter: FolderListInteractorOutput {
}

class FolderListConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = FolderListConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: FolderListViewController) {
        
        let presenter = FolderListPresenter()
        presenter.output = viewController
        
        let interactor = FolderListInteractor()
        interactor.output = presenter
        
        let router = FolderListRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
