//
//  FolderListInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol FolderListInteractorInput {
    
}

protocol FolderListInteractorOutput {
    
}

protocol FolderListDataSource {
    
}

protocol FolderListDataDestination {
    
}

class FolderListInteractor: FolderListInteractorInput, FolderListDataSource, FolderListDataDestination {
    
    var output: FolderListInteractorOutput!
    
    // MARK: Business logic
    

}
