//
//  FolderListPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol FolderListPresenterInput {
    
}

protocol FolderListPresenterOutput: class {
    
}

class FolderListPresenter: FolderListPresenterInput {
    
    weak var output: FolderListPresenterOutput!
    
    // MARK: Presentation logic
    
}
