//
//  FolderListRouter.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol FolderListRouterInput {
    func navigateToPhotoScreen()
}

protocol FolderListRouterDataSource:class {
    
}

protocol FolderListRouterDataDestination:class {
    
}

class FolderListRouter: FolderListRouterInput {
    
    weak var viewController:FolderListViewController!
    weak private var dataSource:FolderListRouterDataSource!
    weak var dataDestination:FolderListRouterDataDestination!
    
    struct SegueIdentifiers {
        static let photoScreen = "ShowPhoto"
    }
    
    init(viewController:FolderListViewController, dataSource:FolderListRouterDataSource, dataDestination:FolderListRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func navigateToPhotoScreen() {
        viewController.performSegue(withIdentifier: SegueIdentifiers.photoScreen, sender: viewController)
    }
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
