//
//  GalleryPhotoInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol GalleryPhotoInteractorInput {
    
}

protocol GalleryPhotoInteractorOutput {
    
}

protocol GalleryPhotoDataSource {
    
}

protocol GalleryPhotoDataDestination {
    
}

class GalleryPhotoInteractor: GalleryPhotoInteractorInput, GalleryPhotoDataSource, GalleryPhotoDataDestination {
    
    var output: GalleryPhotoInteractorOutput!
    
    // MARK: Business logic
    

}
