//
//  GalleryPhotoPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol GalleryPhotoPresenterInput {
    func presentGallery(response: GalleryPhotoScene.GetGalleryPhoto.Response)
}

protocol GalleryPhotoPresenterOutput: class {
    func displayGallery(viewModel: GalleryPhotoScene.GetGalleryPhoto.ViewModel)
}


class GalleryPhotoPresenter: GalleryPhotoPresenterInput {
    
    weak var output: GalleryPhotoPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentGallery(response: GalleryPhotoScene.GetGalleryPhoto.Response) {
        let viewModel = GalleryPhotoScene.GetGalleryPhoto.ViewModel(gallery: response.gallery)
        output.displayGallery(viewModel: viewModel)
    }
}
