//
//  GalleryPhotoRouter.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol GalleryPhotoRouterInput {
    func navigateToPhotoScreen()
}

protocol GalleryPhotoRouterDataSource:class {
    
}

protocol GalleryPhotoRouterDataDestination:class {
    
}

class GalleryPhotoRouter: GalleryPhotoRouterInput {
    
    weak var viewController:GalleryPhotoViewController!
    weak private var dataSource:GalleryPhotoRouterDataSource!
    weak var dataDestination:GalleryPhotoRouterDataDestination!
    
    struct SegueIdentifiers {
        static let photoScreen = "ShowPhoto"
    }
    
    init(viewController:GalleryPhotoViewController, dataSource:GalleryPhotoRouterDataSource, dataDestination:GalleryPhotoRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func navigateToPhotoScreen() {
        viewController.performSegue(withIdentifier: SegueIdentifiers.photoScreen, sender: viewController)
    }
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
