//
//  GalleryPhotoConfigurator.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension GalleryPhotoInteractor: GalleryPhotoViewControllerOutput, GalleryPhotoRouterDataSource, GalleryPhotoRouterDataDestination {
}

extension GalleryPhotoPresenter: GalleryPhotoInteractorOutput {
}

class GalleryPhotoConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = GalleryPhotoConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: GalleryPhotoViewController) {
        
        let presenter = GalleryPhotoPresenter()
        presenter.output = viewController
        
        let interactor = GalleryPhotoInteractor()
        interactor.output = presenter
        
        let router = GalleryPhotoRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
