//
//  GalleryPhotoPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol GalleryPhotoPresenterInput {
    func presentGallery(response: GalleryPhotoScene.GetGalleryPhoto.Response)
}

protocol GalleryPhotoPresenterOutput: class {
    func displayGallery(viewModel: GalleryPhotoScene.GetGalleryPhoto.ViewModel)
}


class GalleryPhotoPresenter: GalleryPhotoPresenterInput {
    
    static var documentsDirectory: URL = {
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        let documentsDirectory = paths[0]
        return documentsDirectory
    }()
    
    weak var output: GalleryPhotoPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentGallery(response: GalleryPhotoScene.GetGalleryPhoto.Response) {
        let photos = parseDataToPhotos(items: response.gallery)
        let viewModel = GalleryPhotoScene.GetGalleryPhoto.ViewModel(photos: photos)
        output.displayGallery(viewModel: viewModel)
    }
    
    func parseDataToPhotos(items: [Item]) -> [INSPhotoViewable] {
        var photos = [INSPhotoViewable]();
        
        for item in items {
            if let filename = item.filename {
                let path = GalleryCell.documentsDirectory.appendingPathComponent(filename)
                let photo = INSPhoto(imageURL: path, thumbnailImage: UIImage())
                if let caption = item.caption {
                    photo.attributedTitle = NSAttributedString(string: caption, attributes: [NSForegroundColorAttributeName: UIColor.white])
                }
                photos.append(photo)
            }
        }
        
        return photos
    }
}
