//
//  GalleryPhotoModels.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct GalleryPhotoScene {
    
    struct GetGalleryPhoto {
        
        struct Response {
            let gallery:[Item]
        }
        
        struct ViewModel {
            let gallery:[Item]
        }
    }
    
}
