//
//  GalleryPhotoInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol GalleryPhotoInteractorInput {
    func getGallery()
    func uploadPhoto(request: GalleryPhotoScene.UploadPhoto.Request)
}

protocol GalleryPhotoInteractorOutput {
    func presentGallery(response: GalleryPhotoScene.GetGalleryPhoto.Response)
}

protocol GalleryPhotoDataSource {
    
}

protocol GalleryPhotoDataDestination {
    var album:Album! {get set}
}

class GalleryPhotoInteractor: GalleryPhotoInteractorInput, GalleryPhotoDataSource, GalleryPhotoDataDestination {
    
    var output: GalleryPhotoInteractorOutput!
    
    var album:Album!
    
    // MARK: Business logic
    
    func getGallery() {
        let items = album.mutableSetValue(forKey: "items")
        let array = items.allObjects as! [Item]
        let response = GalleryPhotoScene.GetGalleryPhoto.Response(gallery: array)
        output.presentGallery(response: response)
    }

    func uploadPhoto(request: GalleryPhotoScene.UploadPhoto.Request) {
        var items = [Item]()
        let images = request.images
        let filenames = request.filenames
        for image in images {
            let index = images.index(of: image)
            let filename = filenames[index!]
            let item = ItemManager.sharedInstance.add(image: image, filename: filename)
            items.append(item)
        }
        
        let itemsInAlbum = album.mutableSetValue(forKey: "items")
        if itemsInAlbum.count > 0 {
            itemsInAlbum.addObjects(from: items)
        } else {
            album.items = NSSet(object: items)
        }
        
        //1
        let managedContext = CoreDataManager.sharedInstance.managedObjectContext

        //2
        do {
            try managedContext.save()
        } catch let error as NSError {
            print("Could not save. \(error), \(error.userInfo)")
        }
        
        getGallery()
    }
}
