//
//  GalleryPhotoPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol GalleryPhotoPresenterInput {
    
}

protocol GalleryPhotoPresenterOutput: class {
    
}

class GalleryPhotoPresenter: GalleryPhotoPresenterInput {
    
    weak var output: GalleryPhotoPresenterOutput!
    
    // MARK: Presentation logic
    
}
