//
//  ImportViewController.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ImportViewControllerInput {
    
}

protocol ImportViewControllerOutput {
    
}

class ImportViewController: UIViewController, ImportViewControllerInput {
    
    var output: ImportViewControllerOutput!
    var router: ImportRouter!
    
    @IBOutlet weak var importTableView: UITableView!

    // MARK: Object lifecycle
    
    struct cellIdentifiers {
        static let importCell = "importCell"
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ImportConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureTableViewOnLoad()
    }
    
    // MARK: Event handling
    
    func configureTableViewOnLoad() {
        let nibName = UINib(nibName: "ImportCell", bundle:Bundle.main)
        importTableView.register(nibName, forCellReuseIdentifier: cellIdentifiers.importCell)
    }
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension ImportViewController: ImportPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(for: segue)
    }
}
