//
//  ImportViewController.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

class ImportViewController: BaseViewController {

    @IBOutlet weak var importTable: UITableView!

    // MARK: Object lifecycle
    
    struct cellIdentifiers {
        static let importCell = "ImportCell"
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()

    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = Key.Screen.importPhoto
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        configureTableViewOnLoad()
    }
    
    // MARK: Event handling
    
    func configureTableViewOnLoad() {
        let nibName = UINib(nibName: "ImportCell", bundle:Bundle.main)
        importTable.register(nibName, forCellReuseIdentifier: cellIdentifiers.importCell)
        importTable.tableFooterView = UIView()
    }
    
    func selectedImportDetailAtIndex(index: Int) {
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let navi  = mainStoryboard.instantiateViewController(withIdentifier: "ChooseAlbum") as! UINavigationController
        let controller = navi.visibleViewController as! ChooseAlbumViewController

        switch index {
        case 0:
            //Photo Library
            controller.importType = .photo
            present(navi, animated: true, completion: nil)
            break
        case 1:
            //Camera
            controller.importType = .camera
            present(navi, animated: true, completion: nil)
            break
        case 2:
            //iTunes Syncing
            let title = "iTunes Syncing"
            let message = "To sync your device:\n1. Connect your iPhone to your computer.\n2. In iTunes, select your iPhone, and then click the apps tab.\n3. Below file sharing, select\"PrivateCorner\" from the list.\n4. Now add, remove, or save photos."
            let alert = GlobalMethods.alertController(title: title, message: message, cancelTitle: "OK")
            present(alert, animated: true, completion: nil)
            break
        case 3:
            //Wireless Syncing
            controller.importType = .wireless
            present(navi, animated: true, completion: nil)
            break
            
        default:
            break
        }
    }
    
    func selectedImportDetail(sender: UIButton) {
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let navi  = mainStoryboard.instantiateViewController(withIdentifier: "ChooseAlbum") as! UINavigationController
        let controller = navi.visibleViewController as! ChooseAlbumViewController
        
        let index = sender.tag
        switch index {
        case 0:
            //Photo Library
            controller.importType = .photo
            present(navi, animated: true, completion: nil)
            break
        case 1:
            //Camera
            controller.importType = .camera
            present(navi, animated: true, completion: nil)
            break
        case 2:
            //iTunes Syncing
            let title = "iTunes Syncing"
            let message = "To sync your device:\n1. Connect your iPhone to your computer.\n2. In iTunes, select your iPhone, and then click the apps tab.\n3. Below file sharing, select\"PrivateCorner\" from the list.\n4. Now add, remove, or save photos."
            let alert = GlobalMethods.alertController(title: title, message: message, cancelTitle: "OK")
            present(alert, animated: true, completion: nil)
            break
        case 3:
            //Wireless Syncing
            controller.importType = .wireless
            present(navi, animated: true, completion: nil)
            break
            
        default:
            break
        }
    }

}

