//
//  ImportInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol ImportInteractorInput {
    
}

protocol ImportInteractorOutput {
    
}

protocol ImportDataSource {
    
}

protocol ImportDataDestination {
    
}

class ImportInteractor: ImportInteractorInput, ImportDataSource, ImportDataDestination {
    
    var output: ImportInteractorOutput!
    
    // MARK: Business logic
    

}
