//
//  ImportConfigurator.swift
//  PrivateCorner
//
//  Created by a on 3/30/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ImportInteractor: ImportViewControllerOutput, ImportRouterDataSource, ImportRouterDataDestination {
}

extension ImportPresenter: ImportInteractorOutput {
}

class ImportConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = ImportConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ImportViewController) {
        
        let presenter = ImportPresenter()
        presenter.output = viewController
        
        let interactor = ImportInteractor()
        interactor.output = presenter
        
        let router = ImportRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
