//
//  LockScreenConfigurator.swift
//  PrivateCorner
//
//  Created by a on 3/9/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension LockScreenInteractor: LockScreenViewControllerOutput, LockScreenRouterDataSource, LockScreenRouterDataDestination {
}

extension LockScreenPresenter: LockScreenInteractorOutput {
}

class LockScreenConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = LockScreenConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: LockScreenViewController) {
        
        let presenter = LockScreenPresenter()
        presenter.output = viewController
        
        let interactor = LockScreenInteractor()
        interactor.output = presenter
        
        let router = LockScreenRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
