//
//  LockScreenModels.swift
//  PrivateCorner
//
//  Created by a on 3/9/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct LockScreenScene {
    enum StartState {
        case FirstStart
        case NotFirst
    }
    
    enum PasscodeState {
        case FirstInput
        case SecondInput
        case SuccessInput
    }
}
