//
//  LockScreenRouter.swift
//  PrivateCorner
//
//  Created by a on 3/9/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LockScreenRouterInput {
    
}

protocol LockScreenRouterDataSource:class {
    
}

protocol LockScreenRouterDataDestination:class {
    
}

class LockScreenRouter: LockScreenRouterInput {
    
    weak var viewController:LockScreenViewController!
    weak private var dataSource:LockScreenRouterDataSource!
    weak var dataDestination:LockScreenRouterDataDestination!
    
    init(viewController:LockScreenViewController, dataSource:LockScreenRouterDataSource, dataDestination:LockScreenRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
