//
//  LockScreenInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/9/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LockScreenInteractorInput {
    
}

protocol LockScreenInteractorOutput {
    
}

protocol LockScreenDataSource {
    
}

protocol LockScreenDataDestination {
    
}

class LockScreenInteractor: LockScreenInteractorInput, LockScreenDataSource, LockScreenDataDestination {
    
    var output: LockScreenInteractorOutput!
    
    // MARK: Business logic
    

}
