//
//  LockScreenPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/9/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol LockScreenPresenterInput {
    
}

protocol LockScreenPresenterOutput: class {
    
}

class LockScreenPresenter: LockScreenPresenterInput {
    
    weak var output: LockScreenPresenterOutput!
    
    // MARK: Presentation logic
    
}
