//
//  PhotoInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol PhotoInteractorInput {
    
}

protocol PhotoInteractorOutput {
    
}

protocol PhotoDataSource {
    
}

protocol PhotoDataDestination {
    
}

class PhotoInteractor: PhotoInteractorInput, PhotoDataSource, PhotoDataDestination {
    
    var output: PhotoInteractorOutput!
    
    // MARK: Business logic
    

}
