//
//  PhotoConfigurator.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension PhotoInteractor: PhotoViewControllerOutput, PhotoRouterDataSource, PhotoRouterDataDestination {
}

extension PhotoPresenter: PhotoInteractorOutput {
}

class PhotoConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = PhotoConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: PhotoViewController) {
        
        let presenter = PhotoPresenter()
        presenter.output = viewController
        
        let interactor = PhotoInteractor()
        interactor.output = presenter
        
        let router = PhotoRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
