//
//  PhotoPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol PhotoPresenterInput {
    func presentPhoto(response: PhotoScene.GetPhoto.Response)
}

protocol PhotoPresenterOutput: class {
    func displayPhoto(viewModel: PhotoScene.GetPhoto.ViewModel)
}

class PhotoPresenter: PhotoPresenterInput {
    
    weak var output: PhotoPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentPhoto(response: PhotoScene.GetPhoto.Response) {
        let viewModel = PhotoScene.GetPhoto.ViewModel(item: response.item)
        output.displayPhoto(viewModel: viewModel)
    }
}
