//
//  PhotoViewController.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol PhotoViewControllerInput {
    
}

protocol PhotoViewControllerOutput {
    
}

class PhotoViewController: UIViewController, PhotoViewControllerInput {
    
    var output: PhotoViewControllerOutput!
    var router: PhotoRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        PhotoConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureSubviews()
    }
    
    // MARK: Event handling
    
    func configureSubviews() {
        self.title = "Photo"
    }
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension PhotoViewController: PhotoPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(for: segue)
    }
}
