//
//  PhotoViewController.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol PhotoViewControllerInput {
    func displayPhoto(viewModel: PhotoScene.GetPhoto.ViewModel)
}

protocol PhotoViewControllerOutput {
    func getPhoto()
}

class PhotoViewController: UIViewController, PhotoViewControllerInput {
    
    var output: PhotoViewControllerOutput!
    var router: PhotoRouter!
    
    @IBOutlet weak var photoImageView: UIImageView!
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        PhotoConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureSubviews()
        configurePhotoViewOnLoad()
    }
    
    // MARK: Event handling
    
    func configureSubviews() {
        self.title = "Photo"
    }
    
    func configurePhotoViewOnLoad() {
        output.getPhoto()
    }
    
    // MARK: Display logic
    func displayPhoto(viewModel: PhotoScene.GetPhoto.ViewModel) {
        let item = viewModel.item
        if let filename = item.filename {
            let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
            let documentsDirectory = paths[0]
            let path = documentsDirectory.appendingPathComponent(filename)
            
            photoImageView.sd_setImage(with: path, placeholderImage: UIImage(), options: [], completed: { (image, error, cacheType, imageURL) in

            })
        }
        
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension PhotoViewController: PhotoPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(for: segue)
    }
}
