//
//  PhotoPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol PhotoPresenterInput {
    
}

protocol PhotoPresenterOutput: class {
    
}

class PhotoPresenter: PhotoPresenterInput {
    
    weak var output: PhotoPresenterOutput!
    
    // MARK: Presentation logic
    
}
