//
//  PhotoModels.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct PhotoScene {
    
    struct GetPhoto {
        
        struct Response {
            let item:Item
        }
        
        struct ViewModel {
            let item:Item
        }
    }
}
