//
//  PhotoInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/16/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol PhotoInteractorInput {
    func getPhoto()
}

protocol PhotoInteractorOutput {
    func presentPhoto(response: PhotoScene.GetPhoto.Response)
}

protocol PhotoDataSource {
    
}

protocol PhotoDataDestination {
    var item:Item! {get set}
}

class PhotoInteractor: PhotoInteractorInput, PhotoDataSource, PhotoDataDestination {
    
    var output: PhotoInteractorOutput!
    var item:Item!
    
    // MARK: Business logic
    
    func getPhoto() {
        let response = PhotoScene.GetPhoto.Response(item: item)
        output.presentPhoto(response: response)
    }

}
