//
//  SettingViewController.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

class SettingViewController: UIViewController {

    @IBOutlet weak var settingTable: UITableView!
    // MARK: Object lifecycle
    
    struct cellIdentifiers {
        static let settingCell = "settingCell"
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()

    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureTableViewOnLoad()
    }
    
    // MARK: Event handling
    
    func configureTableViewOnLoad() {
        let nibName = UINib(nibName: "SettingCell", bundle:Bundle.main)
        settingTable.register(nibName, forCellReuseIdentifier: cellIdentifiers.settingCell)
    }
    
    func selectedSettingAtIndex(index: Int) {
        
//        if index == 0 {
//            router.navigateToPasswordScreen()
//        }
    }

    
}

