//
//  SettingConfigurator.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension SettingInteractor: SettingViewControllerOutput, SettingRouterDataSource, SettingRouterDataDestination {
}

extension SettingPresenter: SettingInteractorOutput {
}

class SettingConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = SettingConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: SettingViewController) {
        
        let presenter = SettingPresenter()
        presenter.output = viewController
        
        let interactor = SettingInteractor()
        interactor.output = presenter
        
        let router = SettingRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
