//
//  SettingInteractor.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol SettingInteractorInput {
    
}

protocol SettingInteractorOutput {
    
}

protocol SettingDataSource {
    
}

protocol SettingDataDestination {
    
}

class SettingInteractor: SettingInteractorInput, SettingDataSource, SettingDataDestination {
    
    var output: SettingInteractorOutput!
    
    // MARK: Business logic
    

}
