//
//  SettingPresenter.swift
//  PrivateCorner
//
//  Created by a on 3/15/17.
//  Copyright (c) 2017 MrAChen. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol SettingPresenterInput {
    
}

protocol SettingPresenterOutput: class {
    
}

class SettingPresenter: SettingPresenterInput {
    
    weak var output: SettingPresenterOutput!
    
    // MARK: Presentation logic
    
}
